---
- name: Playbook to setup my personal machine
  hosts: localhost
  vars:
    personal_dir: "~/stuff"
  tasks:
    - name: install packages
      become: true
      ansible.builtin.dnf:
        name:
          - vim-enhanced
          - tmux
          - nodejs

    - name: setup directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ personal_dir }}"
        - "{{ personal_dir }}/projects"
        - "{{ personal_dir }}/notes"


    - name: Setup dotfiles
      block:
        - name: pull dotfiles
          ansible.builtin.git:
            repo: "git@github.com:resoluteCoder/dotfiles.git"
            dest: "{{ personal_dir }}/dotfiles"

        - name: symlink dotfiles
          ansible.builtin.file:
            src: "{{ personal_dir }}/dotfiles/{{ item }}"
            dest: "~/.{{ item }}"
            state: link
            force: true
          loop:
            - "bashrc"
            - "vimrc"
            - "tmux.conf"
